Tests api
v1690117/rutt pull request #11
Opened 2023-07-11 11:20 UTC by Lazy-ferret

в обработчике на создание нового test suite - id присваиваю сразу (это же обязательный параметр, без него не дает отправить), но как то стремновато - UIный компонент что то делает, какие то id вычисляет, пока не придумал как надо сделать

2023-07-11 22:58 UTC, v1690117 requested changes

2023-07-11 22:58 UTC, v1690117 commented on frontend/src/components/Content/TestSuites/TestSuiteCreationForm/TestSuiteCard/TestSuiteCardItem.tsx/TestSuiteCardItem.styles.ts
> +`;
А зачем так сложно? Делаем один компонент на все случаи и внутри делаем много ифов.  
Если для каждого сделать отдельный компонентик, будет гораздо проще.

2023-07-11 22:58 UTC, v1690117 commented on frontend/src/components/Content/Content.tsx
> +                {/* {suites.map(s => <div><a href='#'>#{s.id}</a> {s.title} {s.description}</div>)} */}
надо убрать, зачем мусор оставлять

2023-07-11 22:58 UTC, v1690117 commented on frontend/src/components/Content/TestSuites/TestSuiteCreationForm/TestSuiteCreationForm.tsx
> +        let newId = lastId ? lastId + 1 : 1;
ид должен с бека формироваться

надо его просто в интерфейсе сделать необязательным

2023-07-11 22:58 UTC, v1690117 commented on frontend/src/components/Content/TestSuites/TestSuiteCreationForm/TestSuiteCreationForm.tsx
> +    const initialFieldValues = {
лучше прям объект передать в useState без объявления переменной

2023-07-11 22:58 UTC, v1690117 commented on frontend/src/components/Content/TestSuites/TestSuiteCreationForm/TestSuiteCreationForm.tsx
> +    const [formFieldValues, setFormFieldValues] = useState(initialFieldValues)
все использования useState лучше сгруппировать и вынести в самый верх компонента

2023-07-11 22:58 UTC, v1690117 commented on frontend/src/components/Content/TestSuites/TestSuiteCreationForm/TestSuiteCreationForm.tsx
> +        if (e.target.outerHTML.includes('textarea')) {
1. А если мы добавим еще поля и у них будут те же input и textarea?  
2. Обращение к html напрямую из реакта можно считать плохой практикой. К этому можно прибегать, когда нет нормальных решений.  

В данном случае надо просто на каждое поле сделать свой обработчик, у нас их не 50, так что ничего страшного, если они будут очень похожи.

2023-07-11 22:58 UTC, v1690117 commented on frontend/src/components/Content/TestSuites/TestSuiteCreationForm/TestSuiteCard/TestSuiteCardItem.tsx/TestSuiteCardItem.tsx
> +export default TestSuiteCardItem;
я использую следующее простое правило при работе с гитом: любой текстовый файл должен заканчиваться пустой строкой. 

Пример объяснения зачем https://medium.com/@alexey.inkin/how-to-force-newline-at-end-of-files-and-why-you-should-do-it-fdf76d1d090e

2023-07-11 23:00 UTC, v1690117 commented
На мелком экране отображается вот так 
<img width="143" alt="image" src="https://github.com/v1690117/rutt/assets/8942600/a23d30d8-45c0-4443-a47f-1fdafeba380f">

2023-07-11 23:05 UTC, v1690117 commented on frontend/src/components/Content/TestSuites/TestSuiteCreationForm/TestSuiteCreationForm.tsx
> +        clearFormFields()
Надо еще обрабатывать успешность операции. Например, задай очень длинный заголовок и попробуй создать. Сервер вернет ошибку, поля очистятся.

2023-07-11 23:06 UTC, v1690117 commented
Еще при большом количестве строк страница начинает скролиться. Главный тулбар и навигация должны быть фиксированы. Скроллиться должен только контент.

2023-07-12 13:59 UTC, Lazy-ferret commented on frontend/src/components/Content/TestSuites/TestSuiteCreationForm/TestSuiteCard/TestSuiteCardItem.tsx/TestSuiteCardItem.styles.ts
> +`;
done

2023-07-12 14:00 UTC, Lazy-ferret commented on frontend/src/components/Content/Content.tsx
> +                {/* {suites.map(s => <div><a href='#'>#{s.id}</a> {s.title} {s.description}</div>)} */}
done

2023-07-12 14:28 UTC, Lazy-ferret commented on frontend/src/components/Content/TestSuites/TestSuiteCreationForm/TestSuiteCreationForm.tsx
> +        let newId = lastId ? lastId + 1 : 1;
done

2023-07-12 14:28 UTC, Lazy-ferret commented on frontend/src/components/Content/TestSuites/TestSuiteCreationForm/TestSuiteCreationForm.tsx
> +    const initialFieldValues = {
done

2023-07-12 14:28 UTC, Lazy-ferret commented on frontend/src/components/Content/TestSuites/TestSuiteCreationForm/TestSuiteCreationForm.tsx
> +    const [formFieldValues, setFormFieldValues] = useState(initialFieldValues)
done

2023-07-12 14:33 UTC, Lazy-ferret commented on frontend/src/components/Content/TestSuites/TestSuiteCreationForm/TestSuiteCreationForm.tsx
> +        if (e.target.outerHTML.includes('textarea')) {
done

2023-07-16 17:32 UTC, v1690117 commented on frontend/src/components/Content/TestSuites/TestSuiteCard/TestSuiteCardItems.tsx/TestSuiteCardItemCount.styles.ts
> +import styled from 'styled-components';
в папке расширение .tsx лишнее

2023-07-16 17:32 UTC, merged