Button component added
v1690117/rutt pull request #5
Opened 2023-06-14 12:38 UTC by Lazy-ferret

2023-06-14 21:26 UTC, v1690117 requested changes

2023-06-14 21:26 UTC, v1690117 commented on frontend/src/App.tsx
> +    // }
А зачем комментить? Надо сразу убирать тогда.

2023-06-14 21:26 UTC, v1690117 commented on frontend/src/components/Button/Button.stories.tsx
> +// }
лишние комменты

2023-06-14 21:26 UTC, v1690117 commented on frontend/src/components/Button/Button.stories.tsx
> +export const Basic: StoryObj<typeof Button> = {
Где-то между блоками одна строка, где-то две - лучше следить за этим и делать однообразно. Но в целом это линтером решится, когда подключим.

2023-06-14 21:26 UTC, v1690117 commented on frontend/src/components/Button/Button.styles.ts
> +  width: 8rem;
Тут ширина фиксирована, в дизайне - в зависимости от текста, там отступы по краям от текста

2023-06-14 21:26 UTC, v1690117 commented on frontend/src/components/Button/Button.styles.ts
> +  font-size: 1.5rem;
лучше в px, как в фигме, чтоб не путаться

2023-06-14 21:26 UTC, v1690117 commented on frontend/src/components/Button/Button.styles.ts
> +  line-height: 2rem;
Тут тоже вроде отличается. В целом надо пройтись, сравнить с десигном.

2023-06-14 21:26 UTC, v1690117 commented on frontend/src/components/Button/Button.styles.ts
> +
Отличаются шрифты:  
тут  
<img width="138" alt="image" src="https://github.com/v1690117/rutt/assets/8942600/061e52f0-1e03-44b6-b8a2-eec073543156">
в фигме  
<img width="124" alt="image" src="https://github.com/v1690117/rutt/assets/8942600/c5f54c7a-f128-4fa9-8c04-4a599464dc6d">

2023-06-16 20:27 UTC, Lazy-ferret commented on frontend/src/components/Button/Button.styles.ts
> +
подправил все, завтра буду что-то новое делать и буду постепенно повторяющиеся стили глобально выносить

2023-06-16 21:45 UTC, v1690117 commented on frontend/public/index.html
> +</body>
лишнее затесалось

2023-06-16 21:45 UTC, merged